### PR TITLE
Add logrotate which peculiarly ubuntu sees no need for

### PR DESCRIPTION
**Pull request by kayiwa**
Hurray Canonical!

### CODE REVIEW

**Comment by kayiwa** [comment]
this fixes https://github.com/pulibrary/vmimages/issues/7 and adds logrotate package

**Comment by jpstroop** [comment]
does it need configuration, or are there reasonable defaults?

**Comment by kayiwa** [comment]
it does need to be configured. I guess in my thinking this was to bootstrap it to make sure it is installed in the base image. In the same way as filebeat and metric beat are included. It otherwise would need to be a role of its own. Hmmm. Will think on that.

**Comment by jpstroop** [comment]
OK. I can merge this if you want to make a separate ticket to follow up. It's a fair point that different application servers might have different rotation/retention needs and policies, though I think some sensible defaults would probably be a good idea.

**Comment by kayiwa** [comment]
created a ticket. Thanks for merging.

**Comment by jpstroop** [comment]
Follow on: #9

**Pull request merged**
